import { array, addresses, bool, boxPath, count, mailRequest, nullableText, object, text, type MailAddress } from '../mailbox/api';
export type { MailAddress } from '../mailbox/api';
import type { ComposeMode, Draft, DraftAttachment, OutboxSubmission } from '@dreampost/protocol';
export type { ComposeMode, Draft, DraftAttachment } from '@dreampost/protocol';
export interface DraftSummary { id: string; mailboxId: string; version: number; state: Draft['state']; mode: ComposeMode; to: MailAddress[]; recipientCount: number; subject: string; updatedAt: string; attachmentCount: number }
export interface EditableDraft { fromAllocationId: string | null; to: MailAddress[]; cc: MailAddress[]; bcc: MailAddress[]; subject: string; bodyText: string; includeQuote: boolean }
export interface SendingIdentity { eligible: boolean; reason: string | null; allocationId: string; mailboxId?: string; address?: string }
export type Submission = OutboxSubmission;
export interface OutboundConfig { enabled: boolean; maxAttachmentBytes?: number; maxMessageBytes?: number; maxRecipients?: number }
export function decodeDraft(raw: unknown): Draft {
  const d = object(raw); const mode = text(d.mode), state = text(d.state);
  if (!['new', 'reply', 'reply_all', 'reply_person', 'forward'].includes(mode) || !['editing', 'queued', 'discarded'].includes(state) || count(d.version) < 1) throw new Error('Invalid draft');
  let quote: Draft['quote'] = null;
  if (d.quote !== null) { const q = object(d.quote), a = object(q.attribution); quote = { sourceMessageId: text(q.sourceMessageId), sourceContentVersion: text(q.sourceContentVersion), include: bool(q.include), text: text(q.text), attribution: { from: addresses(a.from), to: addresses(a.to), cc: addresses(a.cc), subject: text(a.subject), sentAt: nullableText(a.sentAt) } }; }
  return { id: text(d.id), mailboxId: text(d.mailboxId), authorPrincipalId: text(d.authorPrincipalId), version: count(d.version), state: state as Draft['state'], mode: mode as ComposeMode, sourceMessageId: nullableText(d.sourceMessageId), fromAllocationId: nullableText(d.fromAllocationId), to: addresses(d.to), cc: addresses(d.cc), bcc: addresses(d.bcc), subject: text(d.subject), bodyText: text(d.bodyText), quote, attachments: array(d.attachments).map(raw => { const a = object(raw); return { id: text(a.id), filename: text(a.filename), mimeType: text(a.mimeType), sizeBytes: count(a.sizeBytes), sha256: text(a.sha256) }; }), updatedAt: text(d.updatedAt), warnings: array(d.warnings).map(text) };
}
export const draftPath = (box: string, id?: string) => `${boxPath(box)}/drafts${id ? `/${encodeURIComponent(id)}` : ''}`;
export function editable(draft: Draft): EditableDraft { return { fromAllocationId: draft.fromAllocationId, to: draft.to, cc: draft.cc, bcc: draft.bcc, subject: draft.subject, bodyText: draft.bodyText, includeQuote: draft.quote?.include ?? false }; }
export async function createDraft(box: string, body: { mode: ComposeMode; sourceMessageId?: string; replyPerson?: MailAddress; fromAllocationId?: string; mutationKey: string }, csrf: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(draftPath(box), { method: 'POST', body, csrf, signal })).draft); }
export async function loadDraft(box: string, id: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(draftPath(box, id), { signal })).draft); }
export async function listDrafts(box: string, signal: AbortSignal, background = false): Promise<DraftSummary[]> { return array(object(await mailRequest(draftPath(box), { signal, background })).drafts).map(raw => { const item = object(raw); const mode = text(item.mode), state = text(item.state); if (!['new','reply','reply_all','reply_person','forward'].includes(mode) || !['editing','queued','discarded'].includes(state)) throw new Error('Invalid draft summary'); return { id: text(item.id), mailboxId: text(item.mailboxId), version: count(item.version), state: state as Draft['state'], mode: mode as ComposeMode, to: addresses(item.to).slice(0, 3), recipientCount: count(item.recipientCount), subject: text(item.subject), updatedAt: text(item.updatedAt), attachmentCount: count(item.attachmentCount) }; }); }
export async function saveDraft(box: string, id: string, changes: EditableDraft, version: number, key: string, csrf: string, signal?: AbortSignal, quoteExists = true): Promise<Draft> { return decodeDraft(object(await mailRequest(draftPath(box, id), { method: 'PATCH', body: { ...changes, includeQuote: quoteExists ? changes.includeQuote : undefined, expectedVersion: version, mutationKey: key }, csrf, signal })).draft); }
export async function duplicateDraft(box: string, id: string, csrf: string, key: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(`${draftPath(box, id)}/duplicate`, { method: 'POST', csrf, body: { mutationKey: key }, signal })).draft); }
export async function discardDraft(d: Draft, csrf: string, key: string, signal?: AbortSignal): Promise<void> { await mailRequest(`${draftPath(d.mailboxId, d.id)}/discard`, { method: 'POST', body: { expectedVersion: d.version, mutationKey: key }, csrf, signal }); }
export async function uploadDraftAttachment(d: Draft, file: File, csrf: string, key: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(`${draftPath(d.mailboxId, d.id)}/attachments`, { method: 'POST', bytes: file, version: d.version, key, csrf, signal })).draft); }
export async function removeDraftAttachment(d: Draft, id: string, csrf: string, key: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(`${draftPath(d.mailboxId, d.id)}/attachments/${encodeURIComponent(id)}`, { method: 'DELETE', body: { expectedVersion: d.version, mutationKey: key }, csrf, signal })).draft); }
export async function copyDraftAttachment(d: Draft, source: { sourceMailboxId: string; sourceMessageId: string; sourceAttachmentId: string }, csrf: string, key: string, signal?: AbortSignal): Promise<Draft> { return decodeDraft(object(await mailRequest(`${draftPath(d.mailboxId, d.id)}/attachments/copy`, { method: 'POST', body: { ...source, expectedVersion: d.version, mutationKey: key }, csrf, signal })).draft); }
export async function sendingIdentities(signal: AbortSignal): Promise<SendingIdentity[]> { return array(object(await mailRequest('/api/sending-identities', { signal })).identities).map(raw => { const i = object(raw); return { eligible: bool(i.eligible), reason: nullableText(i.reason), allocationId: text(i.allocationId), ...(typeof i.mailboxId === 'string' ? { mailboxId: i.mailboxId } : {}), ...(typeof i.address === 'string' ? { address: i.address } : {}) }; }); }
export function decodeSubmission(raw: unknown): Submission {
  const s = object(raw); const state = text(s.state); if (!['queued', 'dispatching', 'accepted', 'partial', 'failed', 'blocked', 'unknown', 'cancelled'].includes(state)) throw new Error('Invalid submission');
  return { id: text(s.id), mailboxId: text(s.mailboxId), draftId: text(s.draftId), version: count(s.version), state: state as Submission['state'], from: { name: text(object(s.from).name), address: text(object(s.from).address) }, to: addresses(s.to), cc: addresses(s.cc), bcc: addresses(s.bcc), subject: text(s.subject), recipients: array(s.recipients).map(raw => { const r = object(raw); return { address: text(r.address), status: text(r.status) as 'pending' | 'accepted' | 'failed' | 'unknown', code: nullableText(r.code) }; }), errorCode: nullableText(s.errorCode), sentCopyState: text(s.sentCopyState) as Submission['sentCopyState'], sentMessageId: nullableText(s.sentMessageId), createdAt: text(s.createdAt), updatedAt: text(s.updatedAt) };
}
export async function sendDraft(d: Draft, csrf: string, key: string, acknowledgeNotVisible: boolean, signal?: AbortSignal, acknowledgeDuplicate = false): Promise<Submission> { return decodeSubmission(object(await mailRequest(`${draftPath(d.mailboxId, d.id)}/send`, { method: 'POST', body: { expectedVersion: d.version, mutationKey: key, acknowledgeNotVisible, ...(acknowledgeDuplicate ? { acknowledgeDuplicate: true } : {}) }, csrf, signal })).submission); }
export async function listOutbox(box: string, signal: AbortSignal, background = false): Promise<Submission[]> { return array(object(await mailRequest(`${boxPath(box)}/outbox`, { signal, background })).outbox).map(decodeSubmission); }
export async function cancelSubmission(s: Submission, csrf: string): Promise<void> { await mailRequest(`${boxPath(s.mailboxId)}/outbox/${encodeURIComponent(s.id)}/cancel`, { method: 'POST', csrf, body: { expectedVersion: s.version, mutationKey: crypto.randomUUID() } }); }
