import { afterEach, describe, expect, it, vi } from 'vitest';
import { decodeDraft, listDrafts, saveDraft, sendDraft, uploadDraftAttachment, type Draft } from './api';
import { parseTypedRecipients } from './RecipientField';
import { MailApiError, mailRequest } from '../mailbox/api';
const draft: Draft = { id: 'draft', mailboxId: 'box', authorPrincipalId: 'actor', version: 3, state: 'editing', mode: 'reply_all', sourceMessageId: 'source', fromAllocationId: null, to: [], cc: [], bcc: [], subject: 'Re: hello', bodyText: '', quote: { sourceMessageId: 'source', sourceContentVersion: 'sha:2', include: true, attribution: { from: [{ name: 'Sender', address: 'sender@example.test' }], to: [], cc: [], subject: 'hello', sentAt: null }, text: 'Synthetic quoted content' }, attachments: [], updatedAt: '2026-09-27T00:00:00Z', warnings: ['reply_all_not_visible'] };
afterEach(() => vi.unstubAllGlobals());
describe('compose protocol boundary', () => {
  it('decodes structured source attribution and preserves an empty new body', () => { expect(decodeDraft(draft)).toEqual(draft); });
  it('rejects malformed source attribution rather than splitting strings', () => { expect(() => decodeDraft({ ...draft, quote: { ...draft.quote, attribution: { ...draft.quote!.attribution, from: 'Sender <sender@example.test>' } } })).toThrow(); });
  it('saves exactly the expected draft revision and user fields with CSRF', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async () => Response.json({ draft })); vi.stubGlobal('fetch', fetch); const fields = { fromAllocationId: null, to: [], cc: [], bcc: [], subject: 'Edited', bodyText: 'Text', includeQuote: false }; await saveDraft('box', 'draft', fields, 3, 'same-key', 'csrf'); const init = fetch.mock.calls[0]![1] as RequestInit; expect(JSON.parse(init.body as string)).toEqual({ ...fields, expectedVersion: 3, mutationKey: 'same-key' }); expect(init.credentials).toBe('same-origin'); expect(init.redirect).toBe('error'); expect(init.headers).toMatchObject({ 'X-CSRF-Token': 'csrf' }); });
  it('draft list decodes only bounded summaries and never needs quoted/body data', async () => { const summary = { id: 'draft', mailboxId: 'box', version: 3, state: 'editing', mode: 'reply_all', to: [{ name: 'Person', address: 'person@example.test' }], recipientCount: 4, subject: 'Saved draft', updatedAt: '2026-09-27T00:00:00Z', attachmentCount: 2 }; vi.stubGlobal('fetch', async () => Response.json({ drafts: [summary] })); expect(await listDrafts('box', new AbortController().signal)).toEqual([summary]); });
  it('does not send includeQuote for a draft without a quote', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async () => Response.json({ draft })); vi.stubGlobal('fetch', fetch); await saveDraft('box', 'draft', { fromAllocationId: null, to: [], cc: [], bcc: [], subject: '', bodyText: 'Fresh text', includeQuote: false }, 3, 'key', 'csrf', undefined, false); expect(JSON.parse(fetch.mock.calls[0]![1]!.body as string)).not.toHaveProperty('includeQuote'); });
  it('uploads bytes with exact version and UTF-8 filename metadata, not a public URL', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async () => Response.json({ draft })); vi.stubGlobal('fetch', fetch); const file = new File(['fixture'], 'invoice ü.txt', { type: 'text/plain' }); await uploadDraftAttachment(draft, file, 'csrf', 'upload-key'); const [url, init] = fetch.mock.calls[0]! as unknown as [string, RequestInit]; expect(url).toBe('/api/mailboxes/box/drafts/draft/attachments'); expect(init.body).toBe(file); expect(init.headers).toMatchObject({ 'Content-Type': 'application/octet-stream', 'X-Draft-Version': '3', 'X-Attachment-Filename': 'invoice%20%C3%BC.txt', 'X-Mutation-Key': 'upload-key' }); });
  it('passes explicit not-visible acknowledgement only with the frozen revision', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async () => new Response('{}', { status: 409 })); vi.stubGlobal('fetch', fetch); await expect(sendDraft(draft, 'csrf', 'submit-key', true)).rejects.toBeInstanceOf(MailApiError); const init = fetch.mock.calls[0]![1] as RequestInit; expect(JSON.parse(init.body as string)).toEqual({ expectedVersion: 3, mutationKey: 'submit-key', acknowledgeNotVisible: true }); });
  it('reports session expiry without claiming local text was saved or discarded', async () => { vi.stubGlobal('fetch', async () => Response.json({ error: 'unauthenticated' }, { status: 401 })); await expect(mailRequest('/api/example')).rejects.toMatchObject({ status: 401, message: expect.stringContaining('unsaved changes are still here') }); });
});
describe('explicitly typed recipient chips', () => {
  it('keeps commas inside a quoted display name', () => { expect(parseTypedRecipients('"Example, Person" <person@example.test>, other@example.test')).toEqual([{ name: 'Example, Person', address: 'person@example.test' }, { name: '', address: 'other@example.test' }]); });
  it('preserves foreign local-part case and incomplete text for server validation', () => { expect(parseTypedRecipients('MixedCase@example.test; unfinished@')).toEqual([{ name: '', address: 'MixedCase@example.test' }, { name: '', address: 'unfinished@' }]); });
});
