import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import pg from 'pg';
import { afterAll,beforeAll,beforeEach,describe,expect,it } from 'vitest';
import { migrate,appendChange } from '../src/database.js';
import { ApiError } from '../src/errors.js';
import { MailService,registerMailRoutes,indexMessageThread,initializeMessageState,backfillMailState,normalizeMessageId,type MailViewer } from '../src/mail/index.js';
const url=process.env['TEST_DATABASE_URL'];
describe.skipIf(!url)('mail operations with isolated PostgreSQL',()=>{
  const schema=`mail_ops_${randomUUID().replaceAll('-','')}`;let admin:pg.Pool,pool:pg.Pool,service:MailService;
  const alice=randomUUID(),bob=randomUUID(),viewerId=randomUUID(),box=randomUUID(),other=randomUUID();
  const author=(principalId:string,manage=true):MailViewer=>({principalId,permissions:new Set(['mailbox.use',...(manage?['mail.manage']:[])])});
  const a=author(alice),b=author(bob),v=author(viewerId,false),dev:MailViewer={principalId:null,permissions:new Set(['mailbox.use']),developmentMailboxId:box};
  const authorize=(who:MailViewer)=>async(client:pg.PoolClient)=>{await client.query('SELECT id FROM principals WHERE id=$1 FOR UPDATE',[who.principalId]);return who;};
  async function message(options:{mailbox?:string;subject?:string;text?:string;direction?:'inbound'|'outbound';received?:string;thread?:{own?:string;refs?:string[];reply?:string[]}}={}){
    const id=randomUUID(),mailboxId=options.mailbox??box;const client=await pool.connect();
    try{await client.query('BEGIN');await client.query('SELECT id FROM mailboxes WHERE id=$1 FOR UPDATE',[mailboxId]);
      await client.query(`INSERT INTO deliveries(id,mailbox_id,metadata,sha256,raw_size,received_at,parse_status,subject,from_header,to_header,plain_text,direction)
        VALUES($1,$2,'{}',$3,20,$4,'parsed',$5,'Sender <sender@example.test>','reader@example.test',$6,$7)`,[id,mailboxId,'a'.repeat(64),options.received??'2026-09-27T12:00:00.123456Z',options.subject??'Conversation',options.text??'Body',options.direction??'inbound']);
      await client.query('INSERT INTO message_reader_data(delivery_id,parser_version,headers) VALUES($1,2,$2)',[id,{references:options.thread?.refs??[],inReplyTo:options.thread?.reply??[],messageId:options.thread?.own??''}]);
      await initializeMessageState(client,{messageId:id,mailboxId});
      if(options.thread)await indexMessageThread(client,{mailboxId,messageId:id,messageIdHeader:options.thread.own,references:options.thread.refs,inReplyTo:options.thread.reply});
      await appendChange(client,mailboxId,id,'message.received');await client.query('COMMIT');return id;
    }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
  }
  const mutation=async(who:MailViewer,messageId:string,set:{read?:boolean;starred?:boolean;folder?:'inbox'|'archive'|'trash'|'spam'},version?:string)=>service.mutate(box,{operationId:randomUUID(),items:[{id:messageId,version:version??(await service.getState(who,box,messageId)).version}],set},authorize(who));
  beforeAll(async()=>{admin=new pg.Pool({connectionString:url});await admin.query(`CREATE SCHEMA "${schema}"`);pool=new pg.Pool({connectionString:url,options:`-c search_path=${schema}`,max:8});await migrate(pool);service=new MailService(pool);
    for(const [principal,role]of [[alice,1],[bob,1],[viewerId,2]] as const)await pool.query("INSERT INTO principals(id,issuer,subject,app_role,access_enabled) VALUES($1::uuid,'test',$1::text,$2,true)",[principal,role]);
    for(const [mailbox,address]of [[box,'main@example.test'],[other,'other@example.test']])await pool.query('INSERT INTO mailboxes(id,address,name) VALUES($1,$2,$2)',[mailbox,address]);
    for(const principal of[alice,bob,viewerId])await pool.query("INSERT INTO mailbox_memberships(mailbox_id,principal_id,permissions) VALUES($1,$2,ARRAY['read','manage_messages'])",[box,principal]);
  });
  beforeEach(async()=>{await pool.query('TRUNCATE mail_operations,mailbox_changes,mail_message_labels,mailbox_labels,mail_thread_headers,mail_thread_keys,principal_message_flags,mail_message_state,mail_threads,deliveries CASCADE');await pool.query('UPDATE mailboxes SET change_sequence=0,enabled=true');await pool.query("UPDATE mailbox_memberships SET revoked_at=NULL,permissions=ARRAY['read','manage_messages']");});
  afterAll(async()=>{await pool?.end();if(admin){await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await admin.end();}});
  it('keeps flags personal with inbound unread/outbound read defaults',async()=>{const incoming=await message(),sent=await message({direction:'outbound'});expect((await service.getState(a,box,incoming)).read).toBe(false);expect(await service.getState(a,box,sent)).toMatchObject({read:true,folder:'archive',direction:'outbound'});await mutation(a,incoming,{read:true,starred:true});expect(await service.getState(b,box,incoming)).toMatchObject({read:false,starred:false,version:'1:0'});});
  it('requires explicit filing grant and app permission, while readers can set personal flags',async()=>{const m=await message();await mutation(v,m,{read:true});await expect(mutation(v,m,{folder:'trash'})).rejects.toMatchObject({code:'message_management_denied'});await pool.query("UPDATE mailbox_memberships SET permissions=ARRAY['read','manage'] WHERE principal_id=$1",[alice]);await expect(mutation(a,m,{folder:'archive'})).rejects.toMatchObject({code:'message_management_denied'});await mutation(a,m,{starred:true});});
  it('keeps development access read-only and never grants operator content access',async()=>{const m=await message();expect((await service.list(dev,box)).messages).toHaveLength(1);await expect(mutation(dev,m,{read:true},'1:0')).rejects.toMatchObject({code:'development_read_only'});await expect(service.list(a,other)).rejects.toMatchObject({statusCode:404});});
  it('compares only changed version components under concurrent personal/filing edits',async()=>{const m=await message();await Promise.all([mutation(a,m,{read:true},'1:0'),mutation(a,m,{folder:'archive'},'1:0')]);expect(await service.getState(a,box,m)).toMatchObject({read:true,folder:'archive',version:'2:1'});await expect(mutation(a,m,{read:false},'2:0')).rejects.toMatchObject({code:'message_version_conflict'});});
  it('atomically refuses one stale member of a bulk mutation',async()=>{const first=await message(),second=await message();await mutation(a,second,{folder:'archive'});const before=(await pool.query('SELECT change_sequence FROM mailboxes WHERE id=$1',[box])).rows[0].change_sequence;await expect(service.mutate(box,{operationId:randomUUID(),items:[{id:first,version:'1:0'},{id:second,version:'1:0'}],set:{folder:'trash'}},authorize(a))).rejects.toMatchObject({code:'message_version_conflict'});expect((await service.getState(a,box,first)).folder).toBe('inbox');expect((await pool.query('SELECT change_sequence FROM mailboxes WHERE id=$1',[box])).rows[0].change_sequence).toBe(before);});
  it('replays actor-scoped idempotency and refuses payload replacement',async()=>{const m=await message(),operationId=randomUUID();const input={operationId,items:[{id:m,version:'1:0'}],set:{read:true}};const first=await service.mutate(box,input,authorize(a));expect(await service.mutate(box,input,authorize(a))).toEqual(first);await expect(service.mutate(box,{...input,set:{read:false}},authorize(a))).rejects.toMatchObject({code:'operation_id_conflict'});const otherResult=await service.mutate(box,input,authorize(b));expect(otherResult.changeSequence).not.toBe(first.changeSequence);});
  it('undo restores affected components without overwriting independent changes',async()=>{const m=await message();const archived=await mutation(a,m,{folder:'archive'});await mutation(a,m,{read:true});await service.undo(box,archived.operationId,authorize(a));expect(await service.getState(a,box,m)).toMatchObject({folder:'inbox',read:true});});
  it('bulk undo refuses conflicting later changes and is actor-scoped',async()=>{const one=await message(),two=await message();const result=await service.mutate(box,{operationId:randomUUID(),items:[{id:one,version:'1:0'},{id:two,version:'1:0'}],set:{folder:'trash'}},authorize(a));await expect(service.undo(box,result.operationId,authorize(b))).rejects.toMatchObject({code:'operation_not_found'});await mutation(a,two,{folder:'archive'});await expect(service.undo(box,result.operationId,authorize(a))).rejects.toMatchObject({code:'undo_conflict'});expect((await service.getState(a,box,one)).folder).toBe('trash');expect((await pool.query('SELECT deleted_at FROM deliveries WHERE id=$1',[one])).rows[0].deleted_at).toBeNull();});
  it('undo expiry and membership revocation remain enforced on retries',async()=>{const m=await message();const result=await mutation(a,m,{read:true});await pool.query("UPDATE mail_operations SET undo_until=now()-interval '1 second'");await expect(service.undo(box,result.operationId,authorize(a))).rejects.toMatchObject({code:'undo_expired'});await pool.query('UPDATE mailbox_memberships SET revoked_at=now() WHERE principal_id=$1',[alice]);await expect(service.undo(box,result.operationId,authorize(a))).rejects.toMatchObject({statusCode:404});});
  it('labels are scoped, versioned, idempotent and delete invalidates dependent undo',async()=>{const m=await message(),input={operationId:randomUUID(),name:'Receipts',color:'#12AB34'};const label=(await service.mutateLabel(box,'create',undefined,input,authorize(a))).label!;expect(await service.mutateLabel(box,'create',undefined,input,authorize(a))).toMatchObject({label});const applied=await service.mutate(box,{operationId:randomUUID(),items:[{id:m,version:'1:0'}],addLabelIds:[label.id]},authorize(a));expect((await service.list(a,box,{labelId:label.id})).messages).toHaveLength(1);await service.mutateLabel(box,'delete',label.id,{operationId:randomUUID(),expectedVersion:'1'},authorize(a));expect((await service.getState(a,box,m)).labelIds).toEqual([]);await expect(service.undo(box,applied.operationId,authorize(a))).rejects.toMatchObject({code:'undo_conflict'});});
  it('keyset pagination handles timestamp ties, microseconds and filter-bound cursors',async()=>{const ids=[];for(let i=0;i<7;i++)ids.push(await message({received:`2026-09-27T12:00:00.12345${i}Z`}));let cursor:string|undefined;const found:string[]=[];do{const page=await service.list(a,box,{limit:2,cursor});found.push(...page.messages!.map(m=>m.id));cursor=page.nextCursor??undefined;}while(cursor);expect(found).toEqual(ids.reverse());expect(new Set(found).size).toBe(7);const page=await service.list(a,box,{limit:2});await expect(service.list(a,box,{folder:'archive',cursor:page.nextCursor!})).rejects.toMatchObject({statusCode:400});});
  it('literal search supports CJK, escapes wildcards, searches Cc and attachment names without mailbox leakage',async()=>{const m=await message({subject:'Receipt 100%_ done',text:'\u4f60\u597d\u4e16\u754c'});await message({subject:'Receipt 100xx done'});await message({mailbox:other,subject:'Private needle'});await pool.query(`UPDATE message_reader_data SET headers=headers||$2::jsonb WHERE delivery_id=$1`,[m,{cc:'Research <unique-cc@example.test>'}]);const attachment=randomUUID();await pool.query("INSERT INTO attachment_objects(id,sha256,size_bytes,object_key,preview_kind,media_type) VALUES($1::uuid,$2,0,$1::text,'none','text/plain')",[attachment,'a'.repeat(64)]);await pool.query("INSERT INTO message_attachments(delivery_id,ordinal,attachment_id,filename,mime_type) VALUES($1,0,$2,'unique-filename.txt','text/plain')",[m,attachment]);for(const q of['100%_','\u4f60\u597d','unique-cc','unique-filename'])expect((await service.list(a,box,{q})).messages!.map(x=>x.id)).toEqual([m]);expect((await service.list(a,box,{q:'Private needle'})).messages).toHaveLength(0);});
  it('keeps large bodies out of all summary/state/mutation database result rows while retaining scoped body search',async()=>{
    const ids:string[]=[];for(let i=0;i<60;i++)ids.push(await message());
    await pool.query("UPDATE deliveries SET plain_text=repeat('x',1572864)||CASE WHEN id=$1 THEN ' body-only-needle \u4f60\u597d' ELSE '' END WHERE mailbox_id=$2",[ids[0],box]);
    await message({mailbox:other,text:'foreign-body-only-needle'});
    let phase='initial';const observed=new Map<string,{bodyRows:number;projectedRows:number}>();let timedQueries=0;
    const inspectedPool={connect:async()=>{
      const client=await pool.connect();const run=client.query.bind(client);
      return new Proxy(client,{get(target,property){
        if(property==='query')return async(...args:unknown[])=>{
          const result=await (run as (...values:unknown[])=>Promise<pg.QueryResult>)(...args);
          const stats=observed.get(phase)??{bodyRows:0,projectedRows:0};
          for(const row of result.rows??[]){if(Object.hasOwn(row,'plain_text'))stats.bodyRows++;
            if(Object.hasOwn(row,'filing_version')||Object.hasOwn(row,'message_count'))stats.projectedRows++;}
          observed.set(phase,stats);if(typeof args[0]==='string'&&args[0].startsWith('SET LOCAL statement_timeout='))timedQueries++;
          return result;
        };
        if(property==='release')return target.release.bind(target);
        return Reflect.get(target,property,target);
      }});
    }} as unknown as pg.Pool;
    const bounded=new MailService(inspectedPool);
    phase='messages';const page=await bounded.list(a,box,{limit:100});expect(page.messages).toHaveLength(60);
    phase='threads';expect((await bounded.list(a,box,{view:'threads',limit:100})).threads).toHaveLength(60);
    phase='state';expect((await bounded.getState(a,box,ids[0]!)).id).toBe(ids[0]);
    phase='bulk';const changed=await bounded.mutate(box,{operationId:randomUUID(),items:page.messages!.map(row=>({id:row.id,version:row.version})),set:{read:true}},authorize(a));expect(changed.messages).toHaveLength(60);
    for(const name of ['messages','threads','state','bulk']){expect(observed.get(name)?.bodyRows).toBe(0);expect(observed.get(name)!.projectedRows).toBeGreaterThan(0);}
    expect(observed.get('bulk')!.projectedRows).toBe(120);
    phase='search';for(const q of ['body-only-needle','\u4f60\u597d'])expect((await bounded.list(a,box,{q,limit:100})).messages!.map(row=>row.id)).toEqual([ids[0]]);
    expect((await bounded.list(a,box,{view:'threads',q:'body-only-needle',limit:100})).threads!.map(row=>row.lastMessageId)).toEqual([ids[0]]);
    expect((await bounded.list(a,box,{q:'foreign-body-only-needle'})).messages).toEqual([]);
    expect(observed.get('search')?.bodyRows).toBe(0);expect(timedQueries).toBeGreaterThanOrEqual(8);
  });
  it('Sent remains separate from filing and excludes trash/spam',async()=>{const m=await message({direction:'outbound'});expect((await service.list(a,box,{folder:'sent'})).messages!.map(x=>x.id)).toEqual([m]);await mutation(a,m,{folder:'trash'});expect((await service.list(a,box,{folder:'sent'})).messages).toEqual([]);expect((await service.list(a,box,{folder:'trash'})).messages!.map(x=>x.id)).toEqual([m]);});
  it('personal events are actor-scoped, while replay progresses across hidden events',async()=>{const m=await message();const seq=(await service.list(a,box)).changeSequence;await mutation(a,m,{read:true});const unseen=await service.changes(b,box,seq);expect(unseen.changes).toEqual([]);expect(BigInt(unseen.nextSequence)).toBeGreaterThan(BigInt(seq));expect((await service.changes(a,box,seq)).changes[0]?.kind).toBe('message.personal_changed');await mutation(a,m,{folder:'archive'});expect((await service.changes(b,box,seq)).changes.map(e=>e.kind)).toEqual(['message.filing_changed']);});
  it('reports expired event history and rejects future cursors',async()=>{await message();await message();await pool.query('DELETE FROM mailbox_changes WHERE sequence=1');expect((await service.changes(a,box,'0')).resetRequired).toBe(true);await expect(service.changes(a,box,'9999')).rejects.toMatchObject({code:'mail_cursor_ahead'});});
  it('parallel siblings before their parent converge using mailbox-scoped placeholders',async()=>{const ids=await Promise.all([message({thread:{own:'<a@example.test>',refs:['<root@example.test>']}}),message({thread:{own:'<b@example.test>',refs:['<root@example.test>']}})]);const parent=await message({thread:{own:'<root@example.test>'}});const threads=await Promise.all([...ids,parent].map(m=>service.getState(a,box,m)));expect(new Set(threads.map(t=>t.threadId)).size).toBe(1);const listing=await service.list(a,box,{view:'threads',limit:1});expect(listing.threads![0]).toMatchObject({messageCount:3,matchedCount:3,unreadCount:3});await mutation(a,ids[0]!,{read:true});expect((await service.list(a,box,{view:'threads',unread:true})).threads![0]).toMatchObject({messageCount:3,matchedCount:2,unreadCount:2});});
  it('duplicate IDs stay distinct and forged ancestry never merges established threads',async()=>{const first=await message({thread:{own:'<first@example.test>'}}),second=await message({thread:{own:'<second@example.test>'}});const firstThread=(await service.getState(a,box,first)).threadId,secondThread=(await service.getState(a,box,second)).threadId;await message({thread:{own:'<bridge@example.test>',refs:['<first@example.test>','<second@example.test>']}});expect((await service.getState(a,box,first)).threadId).toBe(firstThread);expect((await service.getState(a,box,second)).threadId).toBe(secondThread);expect(firstThread).not.toBe(secondThread);const duplicate=await message({thread:{own:'<first@example.test>'}});expect((await service.getState(a,box,duplicate)).threadId).not.toBe(firstThread);expect((await pool.query('SELECT count(*) AS n FROM deliveries')).rows[0].n).toBe('4');});
  it('IDs are case-sensitive, self references bounded, and cross-mailbox links never grant access',async()=>{const one=await message({thread:{own:'<Case@example.test>'}}),two=await message({thread:{own:'<case@example.test>',refs:['<case@example.test>']}});expect((await service.getState(a,box,one)).threadId).not.toBe((await service.getState(a,box,two)).threadId);const foreign=await message({mailbox:other,thread:{own:'<Case@example.test>'}});await expect(service.thread(a,other,(await pool.query('SELECT thread_id FROM mail_message_state WHERE message_id=$1',[foreign])).rows[0].thread_id)).rejects.toMatchObject({statusCode:404});expect(normalizeMessageId('<"Hello"@Example.test>')).toBe('Hello@Example.test');expect(normalizeMessageId('<bad\r\nInjected@example.test>')).toBeNull();});
  it('metadata backfill is bounded, restartable and preserves personal/filing state',async()=>{const one=await message(),two=await message();await mutation(a,one,{read:true,folder:'archive'});expect(await backfillMailState(pool,{limit:1})).toBe(1);expect(await backfillMailState(pool,{limit:10})).toBe(1);expect(await backfillMailState(pool,{limit:10})).toBe(0);expect(await service.getState(a,box,one)).toMatchObject({read:true,folder:'archive'});expect((await service.getState(a,box,two)).threadId).not.toBeNull();});
  it('does not freeze old reader metadata into singleton threads before parser2 backfill',async()=>{const m=await message();await pool.query("UPDATE message_reader_data SET parser_version=1,headers='{}' WHERE delivery_id=$1",[m]);expect(await backfillMailState(pool,{limit:10})).toBe(0);expect((await service.getState(a,box,m)).threadId).toBeNull();});
  it('does not attach another mailbox label and rolls back personal changes in a mixed invalid request',async()=>{const m=await message(),labelId=randomUUID();await pool.query("INSERT INTO mailbox_labels(id,mailbox_id,name) VALUES($1,$2,'Private label')",[labelId,other]);await expect(service.mutate(box,{operationId:randomUUID(),items:[{id:m,version:'1:0'}],set:{read:true},addLabelIds:[labelId]},authorize(a))).rejects.toMatchObject({code:'label_not_found'});expect(await service.getState(a,box,m)).toMatchObject({read:false,labelIds:[],version:'1:0'});});
  it('cyclic and excessive reference claims remain bounded without recursive graph traversal',async()=>{const first=await message({thread:{own:'<cycle-a@example.test>',refs:['<cycle-b@example.test>']}}),second=await message({thread:{own:'<cycle-b@example.test>',refs:['<cycle-a@example.test>']}});expect((await service.getState(a,box,first)).threadId).toBe((await service.getState(a,box,second)).threadId);const many=await message({thread:{own:'<many@example.test>',refs:Array.from({length:101},(_,i)=>`<ref-${i}@example.test>`)}});const header=(await pool.query('SELECT reference_ids,warnings FROM mail_thread_headers WHERE message_id=$1',[many])).rows[0];expect(header.reference_ids).toHaveLength(100);expect(header.warnings).toContain('reference_limit');});
  it('successful undo retries create no additional changes or flag updates',async()=>{const m=await message();const changed=await mutation(a,m,{read:true});const restored=await service.undo(box,changed.operationId,authorize(a));expect(await service.undo(box,changed.operationId,authorize(a))).toEqual(restored);expect((await service.getState(a,box,m)).version).toBe(restored.messages[0]!.version);expect((await service.list(a,box)).changeSequence).toBe(restored.changeSequence);});
  it('keeps an authorized pending conversation locator usable after parser assignment',async()=>{
    const pending=await message();await pool.query("UPDATE deliveries SET parse_status='pending' WHERE id=$1",[pending]);
    const foreign=await message({mailbox:other,thread:{own:'<foreign-locator@example.test>'}});
    const app=Fastify();app.setErrorHandler((error,request,reply)=>reply.code(error instanceof ApiError?error.statusCode:500).send({error:error instanceof ApiError?error.code:'error'}));
    registerMailRoutes(app,service,{authenticate:async()=>a});await app.ready();
    try{
      const endpoint=`/mailboxes/${box}/threads/${pending}`;
      const initial=await app.inject({url:endpoint});expect(initial.statusCode).toBe(200);expect(initial.json().messages.map((row:{id:string})=>row.id)).toEqual([pending]);
      const child=await message({thread:{own:'<child-locator@example.test>',refs:['<parent-locator@example.test>']}});
      const client=await pool.connect();let threadId:string;
      try{await client.query('BEGIN');threadId=await indexMessageThread(client,{mailboxId:box,messageId:pending,messageIdHeader:'<parent-locator@example.test>',parserVersion:2});await client.query("UPDATE deliveries SET parse_status='parsed' WHERE id=$1",[pending]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
      expect(threadId!).not.toBe(pending);const parsed=await app.inject({url:endpoint});expect(parsed.statusCode).toBe(200);
      expect(new Set(parsed.json().messages.map((row:{id:string})=>row.id))).toEqual(new Set([pending,child]));
      expect(parsed.json().messages.every((row:{threadId:string})=>row.threadId===threadId!)).toBe(true);
      expect((await app.inject({url:`/mailboxes/${box}/threads/${foreign}`})).statusCode).toBe(404);
      const foreignThread=(await pool.query('SELECT thread_id FROM mail_message_state WHERE message_id=$1',[foreign])).rows[0].thread_id;
      expect((await app.inject({url:`/mailboxes/${box}/threads/${foreignThread}`})).statusCode).toBe(404);
      await pool.query('UPDATE deliveries SET deleted_at=now() WHERE id=$1',[pending]);
      expect((await app.inject({url:endpoint})).statusCode).toBe(404);
    }finally{await app.close();}
  });
  it('prefers an actual same-mailbox thread ID over a coincident delivery locator',async()=>{
    const first=await message({thread:{own:'<preferred-original@example.test>'}}),second=await message();
    await pool.query('INSERT INTO mail_threads(id,mailbox_id) VALUES($1,$2)',[first,box]);
    await pool.query('UPDATE mail_message_state SET thread_id=$2 WHERE message_id=$1',[second,first]);
    expect((await service.thread(a,box,first)).messages!.map(row=>row.id)).toEqual([second]);
  });
  it('HTTP rejects duplicate/unexpected query fields and honors transaction CSRF authentication',async()=>{const app=Fastify();app.setErrorHandler((error,request,reply)=>reply.code(error instanceof ApiError?error.statusCode:500).send({error:error instanceof ApiError?error.code:'error'}));registerMailRoutes(app,service,{authenticate:async(request,options)=>{if(options.mutating&&request.headers['x-csrf-token']!=='fixture')throw new ApiError(403,'csrf_rejected');return a;}});await app.ready();try{expect((await app.inject({url:`/mailboxes/${box}/messages?unread=true&unread=false`})).statusCode).toBe(400);expect((await app.inject({url:`/mailboxes/${box}/messages?unexpected=1`})).statusCode).toBe(400);const m=await message();expect((await app.inject({method:'POST',url:`/mailboxes/${box}/messages/mutate`,payload:{operationId:randomUUID(),items:[{id:m,version:'1:0'}],set:{read:true}}})).statusCode).toBe(403);}finally{await app.close();}});
  it('SSE replays only invalidation sequences and terminates when the source session is revoked',async()=>{
    const m=await message();let revoked=false,rechecks=0;const app=Fastify();registerMailRoutes(app,service,{authenticate:async()=>{throw new Error('stream must not renew idle');},captureStream:async()=>({sessionId:randomUUID(),principalId:alice}),recheckStream:async()=>{rechecks++;if(revoked)throw new ApiError(401,'authentication_required');return{viewer:a,expiresAt:Date.now()+10000};},streamPollMs:25,streamLifetimeMs:2000});
    await app.listen({host:'127.0.0.1',port:0});try{const address=app.server.address();if(!address||typeof address==='string')throw new Error('missing address');const response=await fetch(`http://127.0.0.1:${address.port}/mailboxes/${box}/events?after=0`);expect(response.status).toBe(200);const reader=response.body!.getReader();const first=new TextDecoder().decode((await reader.read()).value);expect(first).toContain('event: invalidate');expect(first).not.toContain(m);expect(first).not.toContain('Conversation');revoked=true;let rest='';for(;;){const value=await reader.read();if(value.done)break;rest+=new TextDecoder().decode(value.value);}expect(rest).not.toContain('subject');expect(rechecks).toBeGreaterThan(1);}finally{await app.close();}
  });
});
